<a href="https://colab.research.google.com/github/fernandodeeke/curso_python/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1>Aprendendo Matemática com Python</h1></center>
<center><h2>Curso de Extensão</h2></center>
<center><h3>Fernando Deeke Sasse</h3></center>
<center><h3>CCT - UDESC</h3></center>
<center><h2>Introdução ao NumPy: 1- Arrays</h2></center>

### 1. Introdução

Apresentaremos neste *notebook* uma introdução à biblioteca do Python chamado NumPy (Numerical Python, que é um pacote de código aberto amplamente utilizado em ciência e engenharia. NumPy é o principal pacote para computação científica em Python. Ele executa uma ampla variedade de operações matemáticas avançadas com alta eficiência. Veja a documentação completa do NumPy [aqui](https://numpy.org/doc/stable/index.html).
Após o estudo deste notebook você será capaz de:

- Usar funções NumPy para criar arrays e realizar operações de array NumPy.
- Usar indexação e fatiamento de 1-arrays
- Realizar operações vetoriais com 1-arrays.

### 2. Importando a biblioteca Numpy

Antes de tudo devemos carregar a biblioteca na seção. Um modo de fazer isso é o seguinte:

In [ ]:
import numpy as np

Notemos no comando acima que o nome np é definido pelo usário. Ele será o prefixo a ser usado em todos os comandos da biblioteca NumPy. O nome np é convencionalmente utilizado.

### 3. Criando 1-arrays básicos

O elemento básico do Numpy é um objeto multidimensional chamado *array*. Por exemplo, criemos um array de ordem (*rank*). Um *array* 1-dimensional (1-D ou 1-array) do Numpy pode ser criado da seguinte forma:

In [ ]:
a1 = np.array([1, 2, 3,4,5])
a1

array([1, 2, 3, 4, 5])

Poderíamos também ter escrito:

In [ ]:
a1 = np.array([1, 2, 3,4,5])
print(a1)

[1 2 3 4 5]


Verifiquemos o tipo de objeto:

In [ ]:
print(type(a1))

<class 'numpy.ndarray'>


A princípio o 1-array parace similar a uma lista, que é o elemento mais básico do Python:

In [ ]:
A1 = [1,2,3,4,5]
print(A1)
type(A1)

[1, 2, 3, 4, 5]


list

No entanto, como veremos mais adiante, listas possuem diversas limitações para uso em cálculos numéricos. Podemos  criar um array a partir de uma lista:

In [ ]:
d = [1,2,3,4,5]

In [ ]:
arrd=np.array(d)
print(arrd)
type(arrd)

[1 2 3 4 5]


numpy.ndarray

Consideremos novamente o *1-array* a. Sua forma é

In [ ]:
print(a1.shape)

(5,)


ou seje, ele tem 5 elementos ao longo de um eixo. O índices de um array começam em 0. Por exemplos, selecionemos uma dada componente

In [ ]:
a1[2] # terceira componente

3

In [ ]:
a1[0] # primeira componente

1

A indexação é cíclica. Por exemplo:

In [ ]:
a1[-1] #última componente

5

### 4. Arrays n-dimensionais

Arrays podem ter um número arbitrário de dimensões e formas. Aqui está um exemplo array de 2 dimensões, de formato $4\times 3$:

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6],[3 , 4, 5],[3,1,-2]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 3,  4,  5],
       [ 3,  1, -2]])

Podemos examinar a forma e a dimensão do array por meio dos chamados atributos:

In [ ]:
array_2d.shape

(4, 3)

In [ ]:
array_2d.ndim

2

As primeira dimensão é composta por pelas 4 listas $[ 1,  2,  3]$,  $[ 4,  5,  6]$, $[ 3,  4,  5]$, $[ 3,  1, -2]$. A segunda dimensão é composta pelos 3 elementos de cada lista. A dimensão é sempre igual ao número de componentes na expressão do formato. Os 2-arrays são de especial interesse em matemática, pois estão associados a matrizes, que trataremos em detalhe no próximo curso.

O exemplo a seguir é o de um array 3-dimensional de formato $4\times 2\times 5$:

In [ ]:
# Cria 4x2x5 3-array
array_3d = np.array([[[1, 2, 3, 5, 3],
                      [4, 5, 6, 2, 6]],

                      [[1, 2, 3, 5, 3],
                      [4, 5, 6, 2, 1]],

                      [[10, 11, 12, 23, 35],
                      [13, 14, 15, 31, 12]],

                      [[19, 20, 21, 25, 14],
                      [22, 23, 24, -43, 23]]])

In [ ]:
array_3d.shape

(4, 2, 5)

In [ ]:
array_3d.ndim

3

Nesse curso nos dedicaremos aos 1-arrays. É importante notar que

In [ ]:
A = np.array([1,2,3,4])

é um 1-array:

In [ ]:
print(A.ndim)
print(A.shape)

1
(4,)


Por outro lado,

In [ ]:
B = np.array([[1,2,3,4]])

é um 2-array de formato $1\times 4$:

In [ ]:
print(B.ndim)
print(B.shape)

2
(1, 4)


Esse fato será importante quando abordarmos matrizes e sistemas de equações (curso seguinte).

### 5. Criando 1-arrays especiais
Podemos criar alguns 1-arrays especiais de forma rápida:

In [ ]:
a2 = np.zeros(6) # 1-array com zeros
a2

array([0., 0., 0., 0., 0., 0.])

In [ ]:
a3 = np.ones(6) # 1-array com 1
a3

array([1., 1., 1., 1., 1., 1.])

In [ ]:
a4 = np.random.random(6) # 1-array com elementos aleatórios,
                         #uniformemente distribuídos entre 0 e 1
a4

array([0.45158276, 0.48962307, 0.08665156, 0.34898721, 0.46450142,
       0.68086336])

In [ ]:
a5 = np.random.randn(6) # 1-array com elementos aleatórios,
                        # normalmente distribuídos com média 0 e
                        # desvio padrão 1.
a5

array([ 1.43585662,  0.57244615,  0.14691034,  0.20304244, -0.79117319,
        1.1112371 ])

### 6. Criando 1-arrays com regras de intervalo
Para definir um array num dado intervalo, com um número determinado de elementos igualmente espaçados. Suponhamos que queremos um array com 10 elementos igualmente espaçados no intervalo $[0,1]$:

In [ ]:
a6 = np.linspace(0,1, 10)
a6

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Notemos que se permitirmos 11 elementos, o intervalo será $0,1$:

In [ ]:
a6b = np.linspace(0,1, 11)
a6b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Veremos mais adiante que o comando acima é útil para construir gráficos.

Suponhamos que queremos agora  criar um array com elementos, de 0 a 1, igualmente espaçados com intervalo 0.1:

In [ ]:
a7 = np.arange(0, 1.1, 0.1)
a7

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Criemos um array de 10 a 0, ordenado de forma decrescente,com passo -1:

In [ ]:
np.arange(10, -1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Nos exemplos acima notamos que o último elemento em arange não é incluído.

### 7.  Indexação e fatiamento de *1-arrays*

Vejamos em maior detalhe a manipulação de índices de arrays 1-dimensionais. Seja o array:

In [ ]:
a=np.array([3,4,2,1,7,9])

O primeiro índice do *array* é 0. Por exemplo,

In [ ]:
print(a[0])
print(a[1])

3
4


No entanto, em alguns problemas é útil especificar componentes por índices negativos. Vejamos alguns exemplos para entender como funcionam:

In [ ]:
a[-1] #último elemento do array

9

In [ ]:
a[-2]

7

In [ ]:
a[-3]

1

In [ ]:
a[-5] #primeiro elemento

4

Suponhamos que queremos listar os elementos de um dado array de *N*-dimensional do elemento *n* até o elemento *m*. Por exemplo se queremos as três primeiras componentes de *a* , começando da segunda componente, procedemos do seguinte modo:

In [ ]:
print(a[1:4]) #itens de a[n,m] começam em n e vão até m-1:

[4 2 1]


Usando índices negativos:

In [ ]:
print(a[-4:-1])

[2 1 7]


Se quisermos selecionar as 3 primeiras componentes com incrementos de duas unidades:

In [ ]:
print(a[0:6:2])

[3 2 7]


Algumas técnicas úteis, similares ao Matlab:

In [ ]:
a[2:] #componentes de a[m:] começam em m e vão até o final.

array([2, 1, 7, 9])

In [ ]:
a

array([3, 4, 2, 1, 7, 9])

In [ ]:
a[:-2] # do primeiro elemento até o elemento anterior a a[-2]

array([3, 4, 2, 1])

In [ ]:
a[:4] #componentes de a[:m] começam em 0 e vão até m-1.

array([3, 4, 2, 1])

In [ ]:
a[:] #array completo

array([3, 4, 2, 1, 7, 9])

Podemos concatenar *1-arrays* da seguinte forma:

In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([-1, -2, -3])

In [ ]:
np.concatenate([x,y])

array([ 1,  2,  3,  4,  5, -1, -2, -3])

### 8. Operações matemáticas com  *1-arrays*

Podemos realizar operações matemáticas sobre 1-arrays, elemento por elemento:

In [ ]:
c = np.array([3,5,2,1,4])
2*c # Cada elemento é multiplicado por 2

array([ 6, 10,  4,  2,  8])

In [ ]:
1/c # Calcula o inverso de cada elemento

array([0.33333333, 0.2       , 0.5       , 1.        , 0.25      ])

As operações básicas de 1-arrays de mesma dimensão sãp feitas elemento a elemento por default:

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,-4,5,4,1])
a+b

array([ 7, -2,  8,  8,  6])

In [ ]:
a/b # divisão elemento a elemento

array([ 0.16666667, -0.5       ,  0.6       ,  1.        ,  5.        ])

In [ ]:
a*b # multiplicação elemento a elemento

array([ 6, -8, 15, 16,  5])

In [ ]:
 a**2 # cada elemento é elevado ao quadrado

array([ 1,  4,  9, 16, 25])

In [ ]:
np.sqrt(a) # raiz quadrada de cada elemento

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
np.tan(a) # tangente de cada componente

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

O produto interno de dois vetores pode ser feito do seguinte modo:

In [ ]:
x = np.array([1,2,3])
y = np.array([-1,3,2])

In [ ]:
x.dot(y)

11

De forma equivalente,

In [ ]:
np.dot(x,y)

11

In [ ]:
np.vdot(x,y)

11

O produto vetorial (válido somente para 1-arrays de 3 componentes) pode ser obtido da seguinte forma:

In [ ]:
np.cross(x,y)

array([-5, -5,  5])

Algumas outras operações:  

In [ ]:
print(np.sum(x))  #Soma todos os elementos do array

6


In [ ]:
np.mean(x) #Calcula a média

2.0

In [ ]:
np.std(x) #Calcula o devio padrão

0.816496580927726

In [ ]:
np.median(x) #Mediana

2.0

In [ ]:
print(np.correlate(x,y)) #Coeficiente de correlação

[11]


In [ ]:
print(np.cov(x,y)) #Matriz de covariância

[[1.         1.5       ]
 [1.5        4.33333333]]


In [ ]:
np.percentile(a1,90) #90% dos elementos desse array estão abaixo desse número

4.6

In [ ]:
A = np.array([2,6,3,6,1,2,4,7]) # Ordena em ordem crescente
np.sort(A)

array([1, 2, 2, 3, 4, 6, 6, 7])

In [ ]:
np.sort(A)[::-1] # Ordena em ordem decrescente

array([7, 6, 6, 4, 3, 2, 2, 1])

Números complexos podem ser representados na forma.

In [ ]:
z=2+3j

A operação de conjugação complexa é definida por

In [ ]:
np.conj(2+3j)

(2-3j)

Façamos o produto escalar de dois 1-arrays complexos $z_1\cdot z_2 = (z_1)^{\dagger} z_2$, sendo que o símbolo $\dagger$ denota conjugação hermitiana:

In [ ]:
z1 = np.array([1+2j,1-1j,1+3j])
z2 = np.array([2-2j,1+1j,4-2j])

In [ ]:
np.conj(z1).dot(z2)

(-4-18j)

### 9.   1-arrays booleanos

Podemos criar um array booleano estabelecendo uma condição sobre cada elemento do 1-array numérico:

In [ ]:
import numpy as np

In [ ]:
a = np.array([5,3,4,2,7,2,9,5,6,1])
a > 4

array([ True, False, False, False,  True, False,  True,  True,  True,
       False])

Podemos usar o array booleano para fazer seleção de elementos. Por exemplo,

In [ ]:
a[a>4] # seleciona todos os elementos que são maiores que 4

array([5, 7, 9, 5, 6])

In [ ]:
# condição maior que 2 ou maior que 3:
(a<2) | (a>3)

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True])

In [ ]:
a[(a<2) | (a>3)] #seleciona elementos menores que 2 ou maiores que 3

array([5, 4, 7, 9, 5, 6, 1])

In [ ]:
# condição menor que 5 e maior que 2:
(a<5) & (a>2)

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
a[(a<5) & (a>2)] # seleciona elementos menores que 5 e maiores que 2:

array([3, 4])

Podemos comparar dois arrays, componente a componente:

In [ ]:
a1 = np.array([2,3,4,6,2,4])
a2 = np.array([4,3,5,3,2,1])

In [ ]:
a1[a1<a2] # seleciona elementos de a1 menores que os de a2, respeitando a ordem

array([2, 4])

Similarmente para a2:

In [ ]:
a2[a1<a2]

array([4, 5])

Por exemplo, obtenhamos os elementos de um array que são divisíveis por 4:

In [ ]:
a=np.array([4,5,8,24,22,58,36,90,92,94,96])
a_div4 = a[a%4==0]
a_div4

array([ 4,  8, 24, 36, 92, 96])

Procedimentos relativamente complicados por ser implementados facilmente com Numpy. Por exemplo, Somemos os números inteiros de 0 a 10000, exceto aqueles que podem ser divididos por 4 e 7.

Inicialmente geramos o array de todos os inteiros de 0 a 10000:

In [ ]:
L = np.arange(0,10001,1) #lista os inteiros de 0 a 10000
L

array([    0,     1,     2, ...,  9998,  9999, 10000])

Formamos duas listas:

In [ ]:
L1 = L%4 !=0 #lista booleana dos elementos que não são divisíveis por 4
L1

array([False,  True,  True, ...,  True,  True, False])

In [ ]:
L2 = L%7 !=0 #lista booleana dos elementos que não são divisíveis por 7
L2

array([False,  True,  True, ...,  True,  True,  True])

Notemos que as variáveis lógicas *True* e *False* satisfazem as regras lógicas para *AND*. Por exemplo,

In [ ]:
A1 = np.array([True, False, False, True, False])
A2 = np.array([False, False, True, True, True])

In [ ]:
A1*A2 #AND

array([False, False, False,  True, False])

In [ ]:
A1+A2 #AND

array([ True, False,  True,  True,  True])

Podemos aplicar esse resultado ao nosso problema:

In [ ]:
L1*L2 # não são divisíveis por 4 e 7

array([False,  True,  True, ...,  True,  True, False])

Os números que não são divisíveis por 4 e 7 são, portanto, dados por

In [ ]:
L[L1*L2]

array([   1,    2,    3, ..., 9997, 9998, 9999])

Examinemos alguns elementos:

In [ ]:
L[L1*L2][:30]

array([ 1,  2,  3,  5,  6,  9, 10, 11, 13, 15, 17, 18, 19, 22, 23, 25, 26,
       27, 29, 30, 31, 33, 34, 37, 38, 39, 41, 43, 45, 46])

Podemos agora somar os elementos:

In [ ]:
sum(L[L1*L2])

32147142

Vejamos um exemplo usando arrays com strings. Consideremos o problema de selecionar, numa lista de nomes, aqueles que começam com a letra J. Para isso criamos uma função lambda que seleciona o primeiro elemento de um string ou de de um 1-array:

In [ ]:
f = lambda g: g[0]

Por exemplo,

In [ ]:
f('casa') # primeiro caractere de um string

'c'

In [ ]:
f([2,3,4]) # primeiro elemento de uma lista

2

In [ ]:
f(np.array([2,3,4,9])) # primeiro elemento de um 1-array

2

In [ ]:
f(np.array(['Ana', 'Carlos'])) # primeiro elemento de um 1-array de strings

'Ana'

Tomemos um array de nomes:

In [ ]:
nomes = np.array(['Pedro', 'Joao', 'Jose', 'Luis', 'Maria', 'Cleopatra', 'Theorora', 'Elisa'])

Apliquemos a função `f` a cada elemento do 1-array `nomes`:

In [ ]:
primeira_letra = np.vectorize(f)(nomes)
primeira_letra

array(['P', 'J', 'J', 'L', 'M', 'C', 'T', 'E'], dtype='<U1')

Geramos o array booleano que verifica se a primeira letra do array `nomes` é J:

In [ ]:
primeira_letra_J = primeira_letra=='J'
primeira_letra_J

array([False,  True,  True, False, False, False, False, False])

Podemos agora usar esse array booleano para obter os nomes que começam com J:

In [ ]:
nomes[primeira_letra_J]

array(['Joao', 'Jose'], dtype='<U9')

Vejamos mais um exemplo. Seja a lista de nomes: Achlys, Aether, Aion, Ananke, Chaos, Chronos, Erebus, Eros, Gaia, Hemera, Nesoi, Nyx, Ourea, Phanes, Pontus, Tartarus, Thalassa, Uranus, Aia.  Determine os nomes que começam ou terminam com A.

Criamos o array com nomes:

In [ ]:
Nomes = np.array(["Achlys", "Aether", "Aion", "Ananke", "Chaos", "Chronos", "Erebus",
         "Eros", "Gaia", "Hemera", "Nesoi", "Nyx", "Ourea", "Phanes", "Pontus",
         "Tartarus", "Thalassa", "Uranus", "Aia"])

In [ ]:
f = lambda g: g[0]

In [ ]:
h = lambda g: g[-1]

Formamos um 1-array com a primeira letra de cada nome e outro com a última letra:

In [ ]:
primeira_letra = np.vectorize(f)(Nomes)
primeira_letra

array(['A', 'A', 'A', 'A', 'C', 'C', 'E', 'E', 'G', 'H', 'N', 'N', 'O',
       'P', 'P', 'T', 'T', 'U', 'A'], dtype='<U1')

In [ ]:
ultima_letra = np.vectorize(h)(Nomes)
ultima_letra

array(['s', 'r', 'n', 'e', 's', 's', 's', 's', 'a', 'a', 'i', 'x', 'a',
       's', 's', 's', 'a', 's', 'a'], dtype='<U1')

Definimos o 1-array booleano que verifica, respectivamente, se cada elemento de *primeira_letra* é ou não igual a "A":

In [ ]:
primeira_letra_A = primeira_letra=='A'
primeira_letra_A

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True])

Similarmente para *ultima_letra*:

In [ ]:
ultima_letra_a = ultima_letra =='a'
ultima_letra_a

array([False, False, False, False, False, False, False, False,  True,
        True, False, False,  True, False, False, False,  True, False,
        True])

O seguinte 1-array determina se ao menos um elemento do par ordenado dos 1-arrays *primeira_letra_A* e *ultima_letra_a* é igual a *True*:

In [ ]:
A_ou_a = primeira_letra_A + ultima_letra_a
A_ou_a

array([ True,  True,  True,  True, False, False, False, False,  True,
        True, False, False,  True, False, False, False,  True, False,
        True])

Para encontrar os nomes, basta agora usar esse 1-array booleano como índice de *Nomes*:

In [ ]:
Nomes[A_ou_a]

array(['Achlys', 'Aether', 'Aion', 'Ananke', 'Gaia', 'Hemera', 'Ourea',
       'Thalassa', 'Aia'], dtype='<U8')

### 10. Regras adicionais para manipulação de arrays

#### 10.1 Reshape

A função `numpy.reshape` é uma ferramenta do NumPy que permite alterar a forma de um array existente sem modificar seus dados. Essa função é útil quando você precisa reorganizar os dados para diversos fins, como torná-los compatíveis com outros arrays para cálculos, melhorar a legibilidade ou prepará-los para um tipo específico de processamento.

Por exemplo, suponha que você tenha um 1-array com 6 elementos e queira redimensioná-lo para um 2-array com 2 linhas e 3 colunas:

In [ ]:
import numpy as np

In [ ]:
# Array 1D original
a = np.array([1, 2, 3, 4, 5, 6])

# Redimensiona para um array 2x3
A = np.reshape(a, (2, 3))

In [ ]:
print("Array Original:\n", a)
print("Array Redimensionado (2x3):\n", A)

Array Original:
 [1 2 3 4 5 6]
Array Redimensionado (2x3):
 [[1 2 3]
 [4 5 6]]


Podemos permitir que o NumPy determine automaticamente uma dimensão especificando -1. Aqui, vamos converter o array em 3 linhas, permitindo que o NumPy descubra o número de colunas:

In [ ]:
# Array 1D original
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Redimensiona para um array 3x2 usando -1
array_2d = np.reshape(array_1d, (4, -1))

print("Array Redimensionado (4x2):\n", array_2d)

Array Redimensionado (4x2):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


O redimensionamento é especialmente útil ao trabalhar com dados multidimensionais, como imagens ou lotes de dados. Por exemplo, vamos pegar um array com a forma (2, 3, 4) e redimensioná-lo para (4, 3, 2):

In [ ]:
# Array 3D original
array_3d = np.arange(24).reshape(2, 3, 4)

# Redimensiona para uma forma 3D diferente
array_redimensionado = np.reshape(array_3d, (4, 3, 2))

In [ ]:
print("Array Original (2x3x4):\n", array_3d)
print("Array Redimensionado (4x3x2):\n", array_redimensionado)

Array Original (2x3x4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array Redimensionado (4x3x2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


 Podemos usar reshape para achatar um array em uma única dimensão. Isso é útil quando você precisa realizar operações que requerem um vetor 1D:

In [ ]:
# Array 2D original
array_2d = np.array([[1, 2, 3], [4, 5, 6], [3,4,5]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [ ]:
# Achata o array para 1D
array_achatado = np.reshape(array_2d, -1)
array_achatado

array([1, 2, 3, 4, 5, 6, 3, 4, 5])

### 11. Exercícios

1. Crie um array usando a função `np.arange` que contenha todos os números inteiros de 0 a 20.

2. Crie um array com 15 números igualmente espaçados entre 0 e 1 (inclusive) usando `np.linspace`.

3. Dado o array `arr = np.arange(10)`, obtenha um subarray que contenha os três primeiros elementos de `arr`.

4. Utilize o array do exercício anterior e obtenha um novo array que contenha apenas os elementos ímpares.

5. Dado um array qualquer (por exemplo de 10 componentes) no qual as componentes são ângulos em radianos, determine o correspondente array com ângulos dados em graus.

6. Dado o array `a = np.array([1, 2, 3, 4, 5])`, crie um array booleano que identifique quais elementos de `a` são maiores que 3.

7. Utilizando o array `A = np.array([10, 22, 33, 44, 55, 66, 77, 88, 99]`, crie um array booleano que identifique os elementos maiores que 15 e menores que 120. Use este array booleano para filtrar os elementos correspondentes do array A.

8. Dado o array `B = np.array([3, 6, 9, 12, 15, 18, 21, 24, 27, 30]`, crie um array booleano para selecionar apenas os elementos que são múltiplos de 5.

9. Utilize o array do exercício anterior e obtenha um novo array que contenha apenas os elementos ímpares.

10. Crie dois arrays, um com números pares de 2 a 20 e outro com números ímpares de 1 a 19. Concatene-os em um único array ordenado.

11. Crie dois arrays `a = np.arange(5)` e `b = np.arange(5, 10)`. Calcule a soma elemento a elemento desses dois arrays na forma $\sqrt{a^2+b^2}$.

12. Crie dois arrays, `a = np.array([1, 2, 3])` e `b = np.array([4, 5, 6])`. Concatene-os em um único array.

13. Usando arrays booleanos determine todos o inteiros menores que 200 que são divisíveis por 2 e 3.

14. Crie uma lista com 20 nomes de pessoas (só primeiro nome). Usando arrays booleanos determine os nomes que começam com uma vogal e terminam com a letra "e".

15.  Organizando Dados Meteorológicos.
Você possui um array 1D que contém as temperaturas médias registradas em uma cidade durante 12 meses, mas cada mês tem 3 valores correspondentes à temperatura média no início, no meio e no final do mês. Converta esse array 1D para uma matriz 2D, onde cada linha representa um mês e cada coluna corresponde a um período específico do mês.
